services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./shared:/app/shared
    ports:
      - "3001:3001"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./shared:/app/shared
    ports:
      - "3000:3000"